/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpectateIndexRouteImport } from './routes/spectate.index'
import { Route as SpectateUserIdRouteImport } from './routes/spectate.$userId'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectateIndexRoute = SpectateIndexRouteImport.update({
  id: '/spectate/',
  path: '/spectate/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectateUserIdRoute = SpectateUserIdRouteImport.update({
  id: '/spectate/$userId',
  path: '/spectate/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/spectate/$userId': typeof SpectateUserIdRoute
  '/spectate/': typeof SpectateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/spectate/$userId': typeof SpectateUserIdRoute
  '/spectate': typeof SpectateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/spectate/$userId': typeof SpectateUserIdRoute
  '/spectate/': typeof SpectateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/play'
    | '/spectate/$userId'
    | '/spectate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/play'
    | '/spectate/$userId'
    | '/spectate'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/play'
    | '/spectate/$userId'
    | '/spectate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlayRoute: typeof PlayRoute
  SpectateUserIdRoute: typeof SpectateUserIdRoute
  SpectateIndexRoute: typeof SpectateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectate/': {
      id: '/spectate/'
      path: '/spectate'
      fullPath: '/spectate/'
      preLoaderRoute: typeof SpectateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectate/$userId': {
      id: '/spectate/$userId'
      path: '/spectate/$userId'
      fullPath: '/spectate/$userId'
      preLoaderRoute: typeof SpectateUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlayRoute: PlayRoute,
  SpectateUserIdRoute: SpectateUserIdRoute,
  SpectateIndexRoute: SpectateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
